[package]
name = "sm-match"
description = "GumTree structural matching between two concrete syntax trees, for semantic-merge"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { workspace = true }
sm-cst = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde_json = { workspace = true }
